# Generated by Django 5.0.2 on 2024-02-12 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user_password_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=255, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
