# Generated by Django 5.0.2 on 2024-02-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_user_groups_user_is_superuser_user_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('InProgress', 'In Progress'), ('Complete', 'Complete')], default='InProgress', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='untitled', max_length=255),
        ),
    ]
