# Generated by Django 5.0.2 on 2024-03-03 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(default='60c412cc-3e18-4bed-8f3b-ef70469f1ee6', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='backend.company'),
        ),
    ]
