# Generated by Django 5.0.2 on 2024-03-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('InProgress', 'In Progress'), ('Complete', 'Complete'), ('Deleted', 'Deleted')], default='InProgress', max_length=10),
        ),
    ]
